// worker.js — thin redirect wrapper (auto-generated by site-factory)
// Handles www.example.com and http:// → https://clean-domain at the edge (301).
// Adds HSTS header for security insights compliance (Always Use HTTPS + HSTS).
// Then delegates to the Astro + Cloudflare assets worker.

import astroWorkerMod from './dist/_worker.js/index.js';

const astroWorker = astroWorkerMod.default || astroWorkerMod;

const HSTS_HEADER = 'max-age=31536000; includeSubDomains; preload';

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    const isWww = url.hostname.startsWith('www.');
    const needsHttps = url.protocol === 'http:';

    if (isWww || needsHttps) {
      const cleanHost = url.hostname.replace(/^www\./, '');
      const target = new URL(
        url.pathname + url.search + url.hash,
        `https://${cleanHost}`
      );
      // Build the 301 manually — the Response from Response.redirect() has
      // immutable headers, so an HSTS header set on it is silently dropped.
      return new Response(null, {
        status: 301,
        headers: { Location: target.toString(), 'Strict-Transport-Security': HSTS_HEADER },
      });
    }

    // Delegate to the real Astro-built worker (handles pages + static assets via ASSETS binding)
    let response;
    if (astroWorker.fetch) {
      response = await astroWorker.fetch(request, env, ctx);
    } else {
      response = await astroWorker(request, env, ctx);
    }

    // Re-wrap so headers are mutable — responses from the ASSETS binding (static
    // pages) are immutable, so a direct headers.set() silently no-ops.
    response = new Response(response.body, response);
    response.headers.set('Strict-Transport-Security', HSTS_HEADER);

    return response;
  }
};
