// worker.js — thin redirect wrapper (auto-generated by site-factory)
// Handles www.example.com and http:// → https://clean-domain at the edge (301).
// Adds HSTS header for security insights compliance (Always Use HTTPS + HSTS).
// Then delegates to the Astro + Cloudflare assets worker.

import astroWorkerMod from './dist/_worker.js/index.js';

const astroWorker = astroWorkerMod.default || astroWorkerMod;

const HSTS_HEADER = 'max-age=31536000; includeSubDomains; preload';

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    const isWww = url.hostname.startsWith('www.');
    const needsHttps = url.protocol === 'http:';

    if (isWww || needsHttps) {
      const cleanHost = url.hostname.replace(/^www\./, '');
      const target = new URL(
        url.pathname + url.search + url.hash,
        `https://${cleanHost}`
      );
      const res = Response.redirect(target.toString(), 301);
      res.headers.set('Strict-Transport-Security', HSTS_HEADER);
      return res;
    }

    // Delegate to the real Astro-built worker (handles pages + static assets via ASSETS binding)
    let response;
    if (astroWorker.fetch) {
      response = await astroWorker.fetch(request, env, ctx);
    } else {
      response = await astroWorker(request, env, ctx);
    }

    if (response && response.headers) {
      response.headers.set('Strict-Transport-Security', HSTS_HEADER);
    }

    return response;
  }
};
