// worker.js — thin redirect wrapper (auto-generated by site-factory)
// Handles www.example.com and http:// → https://clean-domain at the edge (301).
// Then delegates to the Astro + Cloudflare assets worker.

import astroWorkerMod from './dist/_worker.js/index.js';

const astroWorker = astroWorkerMod.default || astroWorkerMod;

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    const isWww = url.hostname.startsWith('www.');
    const needsHttps = url.protocol === 'http:';

    if (isWww || needsHttps) {
      const cleanHost = url.hostname.replace(/^www\./, '');
      const target = new URL(
        url.pathname + url.search + url.hash,
        `https://${cleanHost}`
      );
      return Response.redirect(target.toString(), 301);
    }

    // Delegate to the real Astro-built worker (handles pages + static assets via ASSETS binding)
    if (astroWorker.fetch) {
      return astroWorker.fetch(request, env, ctx);
    }
    return astroWorker(request, env, ctx);
  }
};
