// GENERATED by site-factory from specs/centralohio-pressure-pros.spec.mjs — edit the spec, not this file.
// Single source of truth for site-wide structure & nav data.

export const SITE = {
  "brand": "Central Ohio Pressure Washing",
  "domain": "centralohiopressurewashing.com",
  "url": "https://centralohiopressurewashing.com",
  "tagline": "House Soft Washing, Roof Washing & Pressure Cleaning in Columbus, OH",
  "city": "Columbus",
  "state": "OH",
  "stateLong": "Ohio",
  "serviceNoun": "pressure washing",
  "serviceType": "Pressure Washing",
  "schemaType": "LocalBusiness",
  "priceRange": "$$",
  "phoneDisplay": "",
  "phoneHref": "",
  "email": "info@centralohiopressurewashing.com",
  "formsAccessKey": "87342bad-014c-44cd-acd0-508ad1108b5f",
  "slug": "centralohio-pressure-pros",
  "leadEndpoint": "https://leadsink.leadrankllc.workers.dev",
  "gscVerification": ""
} as const;

export const SERVICE_AREAS = [
  "Westerville",
  "Dublin",
  "Sunbury",
  "Powell",
  "New Albany",
  "Hilliard",
  "Upper Arlington",
  "Gahanna",
  "Lewis Center",
  "Delaware",
  "Marysville",
  "Plain City"
] as const;

export const SERVICES = [
  {
    "slug": "house-soft-washing",
    "name": "House Soft Washing",
    "short": "Safe, low-pressure soft washing that removes algae, mold, and mildew from siding and exteriors.",
    "live": true
  },
  {
    "slug": "roof-soft-washing",
    "name": "Roof Soft Washing",
    "short": "Safe roof cleaning that removes algae, moss, and lichen without high pressure or damage to shingles.",
    "live": true
  },
  {
    "slug": "driveway-concrete-pressure-washing",
    "name": "Driveway & Concrete Pressure Washing",
    "short": "Powerful yet controlled pressure washing for driveways, sidewalks, and concrete surfaces.",
    "live": true
  },
  {
    "slug": "deck-patio-cleaning",
    "name": "Deck & Patio Cleaning",
    "short": "Gentle yet effective cleaning for wood decks, composite decks, and paver patios.",
    "live": true
  },
  {
    "slug": "commercial-pressure-washing",
    "name": "Commercial Pressure Washing",
    "short": "Reliable exterior cleaning for commercial properties, storefronts, and multi-unit buildings.",
    "live": true
  }
] as const;

export const NEIGHBORHOODS = [
  {
    "slug": "westerville",
    "name": "Westerville",
    "blurb": "House soft washing, roof washing, and driveway cleaning for Westerville, OH homes and businesses.",
    "live": true
  },
  {
    "slug": "dublin",
    "name": "Dublin",
    "blurb": "Professional soft washing and pressure cleaning for Dublin, OH homes, HOAs, and commercial properties.",
    "live": true
  },
  {
    "slug": "sunbury",
    "name": "Sunbury",
    "blurb": "Soft washing and pressure washing for Sunbury, OH and Delaware County homes and small businesses.",
    "live": true
  },
  {
    "slug": "powell",
    "name": "Powell",
    "blurb": "House, roof, and concrete cleaning for Powell, OH and Liberty Township properties.",
    "live": true
  },
  {
    "slug": "new-albany",
    "name": "New Albany",
    "blurb": "Professional soft washing and pressure cleaning for New Albany, OH homes and businesses.",
    "live": true
  },
  {
    "slug": "hilliard",
    "name": "Hilliard",
    "blurb": "Soft washing, roof cleaning, and concrete pressure washing for Hilliard, OH properties.",
    "live": true
  },
  {
    "slug": "upper-arlington",
    "name": "Upper Arlington",
    "blurb": "House soft washing, roof washing, and concrete cleaning for Upper Arlington, OH homes.",
    "live": true
  },
  {
    "slug": "gahanna",
    "name": "Gahanna",
    "blurb": "Deck, patio, and exterior cleaning for Gahanna, OH homes with wooded, creekside lots.",
    "live": true
  },
  {
    "slug": "delaware",
    "name": "Delaware",
    "blurb": "House soft washing and exterior cleaning for historic and newer Delaware, OH homes.",
    "live": true
  },
  {
    "slug": "lewis-center",
    "name": "Lewis Center",
    "blurb": "Roof and house soft washing for larger, shaded homes in Lewis Center, OH.",
    "live": true
  }
] as const;

export const RESOURCES = [
  {
    "slug": "pressure-washing-cost-columbus",
    "title": "How Much Does Pressure Washing Cost in Columbus, OH? (2026)",
    "blurb": "Typical pricing for house soft washing, roof washing, driveway cleaning, and deck/patio washing in Central Ohio."
  },
  {
    "slug": "how-often-should-you-soft-wash-your-house",
    "title": "How Often Should You Soft Wash Your House in Central Ohio?",
    "blurb": "Recommended schedule for house soft washing in Columbus and suburbs, based on local weather and exposure."
  },
  {
    "slug": "soft-washing-vs-pressure-washing-columbus",
    "title": "Soft Washing vs Pressure Washing in Columbus, OH: Which Is Right for Your Home?",
    "blurb": "When to use soft washing vs pressure washing for siding, roofs, driveways, and decks in Central Ohio."
  },
  {
    "slug": "best-time-to-pressure-wash-house-ohio",
    "title": "Best Time of Year to Pressure Wash Your House in Central Ohio",
    "blurb": "How Ohio's spring pollen, humid summers, fall leaves, and freeze-thaw winters affect the best time to soft wash and pressure wash."
  }
] as const;
